return {
  {
    "catppuccin",
    opts = {
      dim_inactive = { enabled = true, percentage = 0.25 },
      transparent_background = true,
      integrations = {
        nvimtree = false,
        aerial = true,
        headlines = true,
        mason = true,
        neotree = true,
        noice = true,
        telescope = { enabled = true, style = "nvchad" },
        notify = true,
        octo = true,
        sandwich = false,
        semantic_tokens = true,
        symbols_outline = true,
        which_key = true,
        native_lsp = { enabled = true, inlay_hints = { background = false } },
        mini = true,
        leap = true,
        cmp = true,
        neotest = true,
        overseer = true,
        lsp_trouble = true,
        markdown = true,
      },
      custom_highlights = {
        -- disable italics  for treesitter highlights
        TabLineFill = { link = "StatusLine" },
        LspInlayHint = { style = { "italic" } },
        ["@parameter"] = { style = {} },
        ["@type.builtin"] = { style = {} },
        ["@namespace"] = { style = {} },
        ["@text.uri"] = { style = { "underline" } },
        ["@tag.attribute"] = { style = {} },
        ["@tag.attribute.tsx"] = { style = {} },
      },
    },
  },
}
